name: market_pet
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/mascote.png
    - lib/assets/images/banner.jpg
    - lib/assets/images/logo.png
    - lib/assets/images/icon_whatsapp.png
    - lib/assets/images/icons_filters/icon_servicos.png
    - lib/assets/images/icons_filters/icon_acessorios.png
    - lib/assets/images/icons_filters/icon_medicamento.png
    - lib/assets/images/icons_filters/icon_consultas.png
    - lib/assets/images/icons_filters/icon_more.png
    - lib/assets/images/icons_filters/icon_brinquedos.png
    - lib/assets/images/icons_filters/icon_fantasias.png
    - lib/assets/images/icons_filters/icon_racao.png
    - lib/assets/images/icons_filters/icon_snacks.png

  fonts:
    - family: Cherry Bomb
      fonts:
        - asset: lib/assets/fonts/CherryBomb-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: lib/assets/fonts/QuickSand/Quicksand-Bold.ttf
          weight: 900
        - asset: lib/assets/fonts/QuickSand/Quicksand-Light.ttf
        - asset: lib/assets/fonts/QuickSand/Quicksand-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/QuickSand/Quicksand-SemiBold.ttf
          weight: 700

#  # To add assets to your application, add an assets section, like this:
#   assets:
#     - lib/images/
#     - images/mascote.svg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom assets.fonts to your application, add a assets.fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "assets.fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # assets.fonts:
  #   - family: Schyler
  #     assets.fonts:
  #       - asset: assets.fonts/Schyler-Regular.ttf
  #       - asset: assets.fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     assets.fonts:
  #       - asset: assets.fonts/TrajanPro.ttf
  #       - asset: assets.fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding assets.fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
